export const links = [
  {
    main: "Main Menu",
    subMenu: [
      {
        name: "Dashboard",
        href: "/",
        icon: "/images/dashboard.svg",
        icon2: "/images/dashboard.svg",
      },
      {
        name: "Orders",
        href: "/orders",
        icon: "/images/order.svg",
        icon2: "/images/order.svg",
      },
      {
        name: "Transactions",
        href: "/transactions",
        icon: "/images/house.svg",
        icon2: "/images/house-2.svg",
      },
      
    ],
  },
  {
    main: "Organization",
    subMenu: [
      {
        name: "Centers",
        href: "/centers",
        icon: "/images/house.svg",
        icon2: "/images/house-2.svg",
      },
      {
        name: "Hubs",
        href: "/hubs",
        icon: "/images/house.svg",
        icon2: "/images/house-2.svg",
      },
    ],
  },
  {
    main: "Support",
    subMenu: [
      {
        name: "Help",
        href: "/help",
        icon: "/images/house.svg",
        icon2: "/images/house-2.svg",
      },
    ],
  },
];
export const associations = [
  {
    id: 1,
    image: "/images/convenant.png",
    name: "Covenant University (CUALA)",
    members: 8861,
    contact_person: "Suleiman Adu",
    email: "suleimanadu@gmail.com",
    phone: "+234 816 598 5232",
    created_at: "2023-05-06",
    status: "Inactive",
  },
  {
    id: 2,
    image: "/images/ui.png",
    name: "University of Ibadan",
    members: 3536,
    contact_person: "Bode Balu",
    email: "bodebalu@gmail.com",
    phone: "+234 816 598 5232",
    created_at: "2023-05-06",
    status: "Active",
  },
  {
    id: 3,
    image: "/images/oau.png",
    name: "Obafemi Awolowo University",
    members: 1374,
    contact_person: "Suleiman Adu",
    email: "suleimanadu@gmail.com",
    phone: "+234 816 598 5232",
    created_at: "2023-05-06",
    status: "Inactive",
  },
  {
    id: 4,
    image: "/images/convenant.png",
    name: "Covenant University (CUALA)",
    members: 4600,
    contact_person: "Fikayo Adeleke",
    email: "fikayoadeleke@gmail.com",
    phone: "+234 816 598 5232",
    created_at: "2023-05-06",
    status: "Active",
  },
  {
    id: 5,
    image: "/images/oau.png",
    name: "Obafemi Awolowo University",
    members: 7791,
    contact_person: "Bode Balu",
    email: "bodebalu@gmail.com",
    phone: "+234 816 598 5232",
    created_at: "2023-05-06",
    status: "Inactive",
  },
  {
    id: 6,
    image: "/images/ui.png",
    name: "UI Alumni",
    members: 9261,
    contact_person: "Bode Balu",
    email: "bodebalu@gmail.com",
    phone: "+234 816 598 5232",
    created_at: "2023-05-06",
    status: "Active",
  },
  {
    id: 7,
    image: "/images/convenant.png",
    name: "Covenant University (CUALA)",
    members: 2798,
    contact_person: "Suleiman Adu",
    email: "suleimanadu@gmail.com",
    phone: "+234 816 598 5232",
    created_at: "2023-05-06",
    status: "Inactive",
  },
  {
    id: 8,
    image: "/images/oau.png",
    name: "Obafemi Awolowo University",
    members: 2798,
    contact_person: "Suleiman Adu",
    email: "suleimanadu@gmail.com",
    phone: "+234 816 598 5232",
    created_at: "2023-05-06",
    status: "Inactive",
  },
];